### ISSUE TITLE
PlotSquared support does not work in 1.16

### ISSUE THREAD

**Issue by TwinkleToes777** [St3venAU/ArmorStandTools#59]
```
[01:05:55 INFO]: [ArmorStandTools] Enabling ArmorStandTools v3.7.1
[01:05:55 INFO]: [ArmorStandTools] Loading support for v1_16_R3
[01:05:55 WARN]: [ArmorStandTools] Error in config.yml: Invalid material name specifed. Continuing using AIR instead.
[01:05:55 WARN]: java.lang.NoClassDefFoundError: com/plotsquared/core/api/PlotAPI
[01:05:55 WARN]:        at com.gmail.St3venAU.plugins.ArmorStandTools.PlotSquaredHook.<init>(PlotSquaredHook.java:18)
[01:05:55 WARN]:        at com.gmail.St3venAU.plugins.ArmorStandTools.Config.reloadMainConfig(Config.java:177)
[01:05:55 WARN]:        at com.gmail.St3venAU.plugins.ArmorStandTools.Config.reload(Config.java:66)
[01:05:55 WARN]:        at com.gmail.St3venAU.plugins.ArmorStandTools.Config.reload(Config.java:62)
[01:05:55 WARN]:        at com.gmail.St3venAU.plugins.ArmorStandTools.Main.onEnable(Main.java:69)
[01:05:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:05:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[01:05:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[01:05:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518)
[01:05:55 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432)
[01:05:55 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596)
[01:05:55 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:311)
[01:05:55 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[01:05:55 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293)
[01:05:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[01:05:55 WARN]: Caused by: java.lang.ClassNotFoundException: com.plotsquared.core.api.PlotAPI
[01:05:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[01:05:55 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114)
[01:05:55 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[01:05:55 WARN]:        ... 15 more
```
I am using PlotSquared v6, it used to work with v5, but I updated and it stopped working :( and the newest ArmorStandTools version only works with 1.17, so I am stuck.

**Comment by Aurelien30000** [comment]
Understandable, but you should upgrade to 1.17. Otherwise, just copy recent code to the 1.16 release of AST ;)
